### ISSUE TITLE
Feather in long format?

### ISSUE THREAD

**Issue by wyu** [LewisResearchGroup/ms-mint#45]
Hi, I was reading your question about MsFileReader. Looks like you may already have a solution that I'm looking for.
https://github.com/compomics/ThermoRawFileParser/issues/116

Similar to your question, I'd like to have a way to dynamically generate XIC from my DIA proteomics data. Ideally, the mzML file would be reformatted to "feather" file in long format, such that I can extract the XIC with arrow calls in R. The storage space is not a concern as long as the read and filter speed is adequate. 

Thanks!
Wen

**Comment by sorenwacker** [comment]
Hi @wyu ,

you can try

    ms_mint.io.ms_file_to_df()

it reads a MS file. Then you can save it as parquet or feather. The function can read both formats. 

Let me know how it goes.
