### ISSUE TITLE
ERROR:root:process_ms1_files_in_parallel()

### ISSUE THREAD

**Issue by DanielQuiroz97** [LewisResearchGroup/ms-mint#70]
While using 
```
mint.run()
```

I got this error message: 

```

maxtasksperchild: None
ERROR:root:process_ms1_files_in_parallel(): invalid literal for int() with base 10: 'scanId=2702'
ERROR:root:process_ms1_files_in_parallel(): invalid literal for int() with base 10: 'scanId=2456'
ERROR:root:process_ms1_files_in_parallel(): invalid literal for int() with base 10: 'scanId=2711'
ERROR:root:process_ms1_files_in_parallel(): invalid literal for int() with base 10: 'scanId=2499'
```

Seems to be an error related to how *scanId* is passed to int(), if the string *scanId* was not removed before passed to int() 

Notebook in:
[Alkaloids_extraction.pdf](https://github.com/LewisResearchGroup/ms-mint/files/11995746/Alkaloids_extraction.pdf)

**Comment by DanielQuiroz97** [comment]
Sure,

QC file is [Attached](https://github.com/LewisResearchGroup/ms-mint/files/12016215/QC_pos_109.mzML.zip).

MS1 data was acquired with an Agilent QTOF 6546, raw files (.d) were converted to .mxML files with MS convert with the following filters

.

* Peak picking (vendor)
* MS levels: 1 -
* Time scans: 0  to 8 min (trimming the last part of the run)

This is what I see on MZmine:

<img width="1357" alt="Screenshot 2023-07-11 at 11 11 41 AM" src="https://github.com/LewisResearchGroup/ms-mint/assets/18486943/8029230c-711e-4960-8b35-88e21c4f1882">

Best,
Daniel

**Comment by sorenwacker** [comment]
Try updating ms-mint to v0.2.5 `pip install -U ms-mint`.

**Comment by DanielQuiroz97** [comment]
Hi @sorenwacker, 

Thank you for the fast actio. The issue was resolved and I am liking very much how ms-works. I'm attaching some results that I had for my samples.

[Alkaloids_extraction-2.pdf](https://github.com/LewisResearchGroup/ms-mint/files/12021306/Alkaloids_extraction-2.pdf)

Best,
Daniel

**Comment by sorenwacker** [comment]
Thanks for reporting the issue!
