### ISSUE TITLE
Heatmap does not show all files

### ISSUE THREAD

**Issue by DanielQuiroz97** [LewisResearchGroup/ms-mint#74]
I am using ms-mint to integrate 24 targets for 117 mzML files.

The resulting .csv shows 24 unique targets and 117 unique mzML files. However, when I am using `mint.hierarchical_clustering()`, only 1/3 (30) of the samples are shown in the heat map. I am not sure what happened with the rest of the samples.

I am attaching the python notebook.

Best,
Daniel
![Screenshot 2024-10-22 at 9 39 11 AM](https://github.com/user-attachments/assets/899fc6f7-aa5f-442b-9caa-fd14393756af)
![Screenshot 2024-10-22 at 9 39 26 AM](https://github.com/user-attachments/assets/9688481e-fbfe-48c3-b476-d65fdc78e63e)
[Peak_Integration.zip](https://github.com/user-attachments/files/17477091/Peak_Integration.zip)

**Comment by sorenwacker** [comment]
Hi Daniel, 

you can show more files by increasing the size of the image. 

```
mint.plot.hierarchical_clustering(figsize=(8,16))
```

Hope that helps.

**Comment by DanielQuiroz97** [comment]
Hi, 

Yes, It was helpful, I did not realize some labels were not included because  of the figure size.

It worked, thank yo so much
